# Generated by Django 4.1.5 on 2023-02-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hige', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemslisttemplate',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='itemslistitem',
            name='active_item_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hige.itemslist'),
        ),
        migrations.AlterField(
            model_name='itemslisttemplateitem',
            name='items_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hige.itemslisttemplate'),
        ),
    ]
